# Generated by Django 5.2.3 on 2025-06-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Solved', 'Solved'), ('Closed', 'Closed'), ('Resolved ✅', 'Resolved ✅')], default='Open', max_length=15),
        ),
    ]
