# Generated by Django 5.2.3 on 2025-06-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
