# Generated by Django 5.2.3 on 2025-06-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
