# Generated by Django 5.2.3 on 2025-06-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_menu_id_menu_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='role_id',
            new_name='role',
        ),
    ]
