# Generated by Django 5.2.3 on 2025-06-23 03:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_problem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.CharField(default=uuid.uuid4, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Module',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.module'),
        ),
    ]
