# Generated by Django 5.2.3 on 2026-07-29 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleshootingImport',
            fields=[
                ('import_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='troubleshooting_imports/%Y/%m/')),
                ('original_file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Completed With Errors'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('imported_records', models.PositiveIntegerField(default=0)),
                ('skipped_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Troubleshooting Import',
                'verbose_name_plural': 'Troubleshooting Imports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='problem',
            name='error_code',
            field=models.CharField(blank=True, db_index=True, help_text='Example: AI8808', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='function_name',
            field=models.CharField(blank=True, help_text='Example: GL A/C Definition Maintenance', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='source_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('word_import', 'Word Import'), ('excel_import', 'Excel Import')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, help_text='Example: 0015100', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='source_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='core.department'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='core.module'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Solved', 'Solved'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Open', max_length=15),
        ),
        migrations.AlterField(
            model_name='problem',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='core.usergroup'),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.problem'),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='problemattachment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('text', 'Text Explanation'), ('code', 'Code Fix'), ('config', 'Configuration Change'), ('workaround', 'Workaround'), ('documentation', 'Documentation Link'), ('imported', 'Imported Resolution')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['error_code'], name='core_proble_error_c_9825b0_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['transaction_code'], name='core_proble_transac_12daf3_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['status'], name='core_proble_status_9463da_idx'),
        ),
        migrations.AddField(
            model_name='troubleshootingimport',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleshooting_imports', to=settings.AUTH_USER_MODEL),
        ),
    ]
