# Generated by Django 5.2.3 on 2025-06-17 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemattachment',
            name='problemattachment_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
