# Generated by Django 5.2.3 on 2026-07-29 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_troubleshootingimport_alter_problem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
