# Generated by Django 5.2.3 on 2025-06-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='module_name',
        ),
        migrations.AlterField(
            model_name='module',
            name='module_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
