# Generated by Django 5.2.3 on 2026-07-30 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_problemattachment_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('function_name', models.CharField(blank=True, default='', max_length=500)),
                ('transaction_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('root_cause', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='core.module')),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'verbose_name_plural': 'Knowledge Articles',
                'ordering': ['error_code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticleImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='knowledge_articles/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.knowledgearticle')),
            ],
            options={
                'verbose_name': 'Knowledge Article Image',
                'verbose_name_plural': 'Knowledge Article Images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGuide',
            fields=[
                ('guide_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_guides', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_guides', to='core.module')),
            ],
            options={
                'verbose_name': 'Knowledge Guide',
                'verbose_name_plural': 'Knowledge Guides',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGuideVersion',
            fields=[
                ('version_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(default='1.0', max_length=30)),
                ('source_file', models.FileField(upload_to='knowledge_guides/%Y/%m/')),
                ('original_file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Completed With Errors'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_articles', models.PositiveIntegerField(default=0)),
                ('imported_articles', models.PositiveIntegerField(default=0)),
                ('skipped_articles', models.PositiveIntegerField(default=0)),
                ('failed_articles', models.PositiveIntegerField(default=0)),
                ('import_log', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.knowledgeguide')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_knowledge_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Guide Version',
                'verbose_name_plural': 'Knowledge Guide Versions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='guide_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.knowledgeguideversion'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeguideversion',
            constraint=models.UniqueConstraint(fields=('guide', 'version_number'), name='unique_knowledge_guide_version'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['error_code'], name='core_knowle_error_c_96cf55_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['transaction_code'], name='core_knowle_transac_ac5c13_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['is_published'], name='core_knowle_is_publ_97de7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticle',
            constraint=models.UniqueConstraint(fields=('guide_version', 'error_code', 'title'), name='unique_article_per_guide_version'),
        ),
    ]
