# Generated by Django 5.2.3 on 2025-06-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_problemattachment_problemattachment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu',
            new_name='menu_id',
        ),
    ]
