# Generated by Django 5.2.3 on 2025-06-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_menu_menu_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('menu_id', 'role')},
        ),
    ]
