# Generated by Django 5.2.3 on 2025-06-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='id',
            new_name='department_id',
        ),
    ]
