# Generated by Django 5.2.3 on 2025-06-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_menu_permission_menu_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permission'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Problem', 'verbose_name_plural': 'Problem'},
        ),
        migrations.AlterModelOptions(
            name='problemtag',
            options={'verbose_name': 'ProblemTag', 'verbose_name_plural': 'ProblemTag'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Role'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solution'},
        ),
        migrations.AlterModelOptions(
            name='solutionattachment',
            options={'verbose_name': 'SolutionAttachment', 'verbose_name_plural': 'SolutionAttachment'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tag'},
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
