# Generated by Django 5.2.3 on 2025-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_id_department_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
