# Generated by Django 5.2.3 on 2025-06-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_problem_id_problem_problem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemattachment',
            name='id',
        ),
        migrations.AddField(
            model_name='problemattachment',
            name='problemattachment_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
