# Generated by Django 5.2.3 on 2025-06-18 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_department_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.menu'),
        ),
    ]
