# Generated by Django 5.2.3 on 2025-06-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_permission_menu_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('menu_id', 'role')},
        ),
    ]
