# Generated by Django 5.2.3 on 2025-06-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_problemattachment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='id',
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
