# Generated by Django 5.2.3 on 2025-06-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_permission_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='menu_id',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, to='core.menu'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('menu_id', 'role'), name='unique_permission'),
        ),
    ]
