# Generated by Django 5.2.3 on 2025-06-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_solution_id_solution_solution_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user_group_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usergroup'),
        ),
    ]
