# Generated by Django 5.2.3 on 2025-06-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usergroup_problem_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usergroup'),
        ),
    ]
