# Generated by Django 5.2.3 on 2025-06-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_permission_menu_id_alter_permission_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='core.menu'),
        ),
    ]
